FROM mcr.microsoft.com/vscode/devcontainers/base:1-ubuntu-22.04

RUN apt update && apt install -y tig tmux vim
RUN curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.2.0/aqua-installer | bash
